# docker-compose run --rm  --service-ports angular bash
# the above command will start a container for this one-off angular development env in a bash shell
# environment variables is defined in .env file or the local env
version: "3"
services:
  angular:
    # replace username/repo:tag with your name and image details
    image: trion/ng-cli
    volumes:
      - "$PWD:/code"
      - "$HOME:/home"
      - "/var:/var"
    working_dir: /code
    ports:
      - "4200:4200"
      - "9876:9876"

